title: Docker Extensions
show_downloads: true
twitter_username: collabnix
github_username: collabnix
youtube: c/Collabnix
post_search: true
google_analytics:
theme: jekyll-theme-hacker
jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
